### ISSUE TITLE
Controlling width of figures in flex container

### ISSUE THREAD

**Issue by ebeshero** [ACPSU/portfolio#1]
Hi @ACPSU ! Here's what we were talking about after class just now. You have something like this:

```css
Figure{
    width: 20%;
    background: /*#FFD700*/gold
}

div.flex {
display:flex;
}
```

First, change the `Figure` to `figure` to match the real HTML element .
Then try removing the width property, b/c it's now being controlled by the flex container.

By default, with no flex property assigned, all child elements of a flex container get a flex property of 1. So they are NOW displaying in a 1:1:1 ratio.

To make the dear data image wider, add a `@class` attribute of like `<figure class="wide">` to its parent figure, and then you can give it a flex property of like 2 or something, like so:

```css
figure.wide {
      flex:2;
}
```
